# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  matrix:
    - COMPOSER_PARAMETER=--prefer-lowest
    - COMPOSER_PARAMETER=

# optionally set up exclutions and allowed failures in the matrix
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - travis_retry pecl install ast
  - travis_retry pecl install igbinary

install:
  - travis_retry composer update -n --no-progress --no-suggest $COMPOSER_PARAMETER

script:
  - composer ci

# allow builds for all branches
branches:
  only:
    - /.*/

# disable shallow cloning
git:
  depth: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.npm

# Notifications
notifications:
  email:
    on_success: never

